# Generated by Django 2.2 on 2022-04-17 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=10, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=20, verbose_name='Фамилия')),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('isbn', models.IntegerField(default=1)),
                ('publish_year', models.CharField(default='', max_length=4, verbose_name='Год выпуска')),
                ('pagination', models.IntegerField(default=1, verbose_name='Количество страниц')),
                ('author', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app_lib.Author')),
            ],
        ),
    ]
